### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by usb248** [daspinola/video-stream-sample#1]
[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
Listening on port 3000!
**SyntaxError: Identifier 'head' has already been declared**

**Comment by pudg** [comment]
Changed ` const head = {` to `head = {` and everything worked for me.

**Comment by daspinola** [comment]
Late reply for reference, due to lack of information on how to replicate the issue I will close this.

**Comment by philwesthart** [comment]
I had the same issue. ```const head = { ``` to ```const my_head = {```
