### ISSUE TITLE
[ nodemon ] app crashed - waiting for file changes before starting 

### ISSUE THREAD

**Issue by rahmandikahaekal** [daspinola/video-stream-sample#4]
i've clone this repo .
go to inside folder and wrote `npm install` for including node . 
but when i want to start it `npm start`, it doesn't start .
![screenshot from 2018-10-04 09-04-53](https://user-images.githubusercontent.com/19472351/46449164-a0c36200-c7b4-11e8-8681-da8169e1944c.png)

**Comment by vujovicigor** [comment]
Error: listen EADDRINUSE ::3000
means: port 3000 is already in use on your computer
You can change listening port in server.js file, line 46

`app.listen(3000, function () {
  console.log('Listening on port 3000!')
})`

**Comment by mirajehossain** [comment]
in the terminal, write killall node, then npm start again.

**Comment by con-fid** [comment]
Am having same issue but PORT changes didn't work.
