### ISSUE TITLE
multiple videos...

### ISSUE THREAD

**Issue by justjim1220** [daspinola/video-stream-sample#6]
I want to have the ability to have multiple videos in the asset directory and instead of a start/stop button, I would like to have  Previous & Next buttons. Or, since I would only have 5 videos in the assets folder, maybe a button for each video? Maybe have the buttons for each video across the bottom (row) or down either side (column). Also, would there be a way to set the size of the video container? Like declaring a static height and width so it doesn't change to the default of each video?

sorry for all the questions, but this is a very cool and I am quite a newbie to this type of code.
(having mainly js with css is my only real experience. The HTML snippet confused me a bit 🤔

**Comment by daspinola** [comment]
I guess you might have figured it out in the meantime but I will leave this as a guideline for anyone else that might have similar questions.

If you have two videos, let's say **sample_1** and **sample_2** you can on the `server.js` replace the path with something like:

```js
const path = `assets/${req.query.name}.mp4`
```

And on the `index.html` add the name of the video you want to load:

```html
<video id="videoPlayer" controls muted="muted" autoplay>
  <source src="/video?name=sample_1" type="video/mp4">
</video>
```

As for switching videos, if you done the above, let's say you have a button to load the second video and you add a `click` event:

```html
<video id="videoPlayer" controls muted="muted" autoplay>
  <source src="/video?name=sample_1" type="video/mp4">
</video>

<button class="video2">Second video</button>

<script src="index.js"></script>
```

```js
document.addEventListener('DOMContentLoaded', init, false)

function init() {
  const video2 = document
    .querySelector('.video2')
  
  video2
    .addEventListener('click', () => {
      const videoPlayer = document
        .getElementById('videoPlayer')
      const videoPlayerSource = document
        .querySelector('#videoPlayer source')

      videoPlayerSource
        .setAttribute('src', '/video?name=sample_2')

      videoPlayer.load()
    })
}
```

For the size of the video you can either add the width and height with css (preferred) or add it on the `index.html`

```html
<video id="videoPlayer" width="800" height="450" controls muted="muted" autoplay>
  <source src="/video?name=sample_1" type="video/mp4">
</video>
```
